GET https://localhost:7183/bp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmIyZmFiMi1mM2ZjLTRhZjItODVlYS1kNDRhNWM4MWYyN2EiLCJqdGkiOiIwZjE0MDFjOC1kZjY3LTQ1YTktOTJhMC1iZWM3MjZlNzdkYTQiLCJuYW1lIjoibXByYXR0aW5nZXIiLCJVTVVJRCI6IjA2YjJmYWIyLWYzZmMtNGFmMi04NWVhLWQ0NGE1YzgxZjI3YSIsImV4cCI6MTcyOTE5ODI2MSwiaXNzIjoiVXNlck1hbmFnZW1lbnQiLCJhdWQiOiJVc2VyTWFuYWdlbWVudCJ9.0-70ZhfhccWXJoq7ds0uhFHRbNjHcj9PaU5uQUpt15M